### ISSUE TITLE
Error when doing 'auth' in Jabber::HTTPBinding::Client

### ISSUE THREAD

**Issue by cryptomatictrader** [lnussbaum/xmpp4r#33]
Basically I'm trying to get RID and SID so that I can pass them to the javascript code. I'm able to connect to the server using Jabber::Client without any problem and I am also able to use a GUI client with BOSH to login without any problem. However, I got this error when doing 'auth' in Jabber::HTTPBinding::Client.

Any help is greatly appreciated. Thank you!

```
require 'xmpp4r/httpbinding/client'
a = Jabber::HTTPBinding::Client.new("user01@jabber.example.com/laptop")
a.connect("http://localhost:5280/http-bind")
a.auth("password")
Jabber::ClientAuthenticationFailure: undefined method `flush' for nil:NilClass
from /usr/local/rvm/gems/ruby-2.0.0-p195/gems/xmpp4r-0.5/lib/xmpp4r/client.rb:118:in `rescue in auth'
from /usr/local/rvm/gems/ruby-2.0.0-p195/gems/xmpp4r-0.5/lib/xmpp4r/client.rb:108:in `auth'
from (irb):5
from /usr/local/rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
from /usr/local/rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
from /usr/local/rvm/gems/ruby-2.0.0-p195/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

**Comment by cryptomatictrader** [comment]
I figured out it is the same issue as https://github.com/ln/xmpp4r/issues/22
