### ISSUE TITLE
Error when trying to get SID and RID from BOSh

### ISSUE THREAD

**Issue by coderhs** [lnussbaum/xmpp4r#37]
This the code i used to get the sid and rid from the bosh service of prosody. 

``` Ruby
require 'xmpp4r/httpbinding/client'

@client = Jabber::HTTPBinding::Client.new("ruby@example.com")
@client.connect("http://example.com/http-bind")
@client.auth("password")

sid = @client.instance_variable_get("@http_sid")
rid = @client.instance_variable_get("@http_rid")

puts sid
puts rid
```

Error message

```
/usr/local/lib/ruby/gems/1.9.1/gems/xmpp4r-0.5/lib/xmpp4r/client.rb:118:in `rescue in auth': undefined method `kill' for nil:NilClass (Jabber::ClientAuthenticationFailure)
    from /usr/local/lib/ruby/gems/1.9.1/gems/xmpp4r-0.5/lib/xmpp4r/client.rb:108:in `auth'
    from /home/hsps/sandbox/post.rb:5:in `<main>'
```

**Comment by coderhs** [comment]
I have found an updated version of this gem, using which I was able to solve my problem. Just posting it here so that it would be helpful for others who might have a similar problem as mine. 

Updated gem: 

```
https://github.com/mad-p/xmpp4r
```

it can be installed using the command 

```
gem install mad-p-xmpp4r
```

code will remain the same.
